name: Test and Deploy for dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack:latest
        ports:
          - 6379:6379
          - 8001:8001
        env:
          REDIS_DOCKER_PORT: 6379
          FLASK_SECRET: mysecretkey
          HOST_IP: 127.0.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python test.py

      - name: Stop Redis service
        run: |
          CONTAINER_ID=$(docker ps --quiet --filter "name=redis-stack")
          if [ -n "$CONTAINER_ID" ]; then
            docker stop "$CONTAINER_ID"
          fi

        if: always()

      - name: Merge dev branch to main
        if: ${{ github.ref == 'refs/heads/dev' && success() }}
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge dev branch to main'
          title: 'Merge dev branch to main'
          body: 'This pull request merges the dev branch to main.'
          branch: 'main'
          base: 'dev'