name: Automatic Test and Merge

on:
  push:
    branches: [ dev ]

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python test.py

    - name: Merge changes into main
      if: success()
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pullRequests } = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: 'main',
            head: 'dev',
            state: 'open'
          });
          if (pullRequests.length === 0) {
            console.log('No open pull requests from dev to main.');
            return;
          }
          const { number: prNumber } = pullRequests[0];
          await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            merge_method: 'squash'
          });
