name: Test and Deploy for dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack:latest
        ports:
          - 6379:6379
          - 8001:8001
        env:
          REDIS_DOCKER_PORT: 6379
          FLASK_SECRET: mysecretkey
          HOST_IP: 127.0.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python test.py

      - name: Stop Redis service
        run: |
          CONTAINER_ID=$(docker ps --quiet --filter "name=redis-stack")
          if [ -n "$CONTAINER_ID" ]; then
            docker stop "$CONTAINER_ID"
          fi

        if: always()

      - name: Push changes to main branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-commit changes after passing tests"
          commit_options: "--no-verify"
          branch: main
          file_pattern: "**/*"
          pull_branch: dev
          commit_user_email: nguyenkduywork@gmail.com
          commit_user_name: nguyenkduywork
        if: success()
